tls:
  certificates:
    - certFile: /etc/ssl/traefik/localhost.pem
      keyFile: /etc/ssl/traefik/localhost-key.pem
  stores:
    default:
      defaultCertificate:
        certFile: /etc/ssl/traefik/localhost.pem
        keyFile: /etc/ssl/traefik/localhost-key.pem
